# Generated by Django 4.2.3 on 2023-09-03 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_category_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
